// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3hSSbwDr8_G3ToQQ-cBocsN9pMQHcKo0',
    appId: '1:979117053331:web:55bc8bd4f27c6b9c7e0466',
    messagingSenderId: '979117053331',
    projectId: 'd4rkr0n1n-demo-app',
    authDomain: 'd4rkr0n1n-demo-app.firebaseapp.com',
    storageBucket: 'd4rkr0n1n-demo-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7ai473MRKhKGaptfdseZ8jXOvpF5v5pQ',
    appId: '1:979117053331:android:3ad6f6f17e60fafe7e0466',
    messagingSenderId: '979117053331',
    projectId: 'd4rkr0n1n-demo-app',
    storageBucket: 'd4rkr0n1n-demo-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS6oBe9ic-U-Z_Te19nHpZUt9v0W8HJpM',
    appId: '1:979117053331:ios:9cf4a1349367263e7e0466',
    messagingSenderId: '979117053331',
    projectId: 'd4rkr0n1n-demo-app',
    storageBucket: 'd4rkr0n1n-demo-app.appspot.com',
    iosClientId: '979117053331-ppprpdb8rviv8i0gbok0400dcqfrpgga.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS6oBe9ic-U-Z_Te19nHpZUt9v0W8HJpM',
    appId: '1:979117053331:ios:458ace90a485ee4c7e0466',
    messagingSenderId: '979117053331',
    projectId: 'd4rkr0n1n-demo-app',
    storageBucket: 'd4rkr0n1n-demo-app.appspot.com',
    iosClientId: '979117053331-tdb7es1uo3qoc3h7tpmadmkoglirirf9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationDemo.RunnerTests',
  );
}
